name: unlighthouse-desktop

on:
  push:
    branches: [main, dev]

jobs:
  unlighthouse-desktop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install unlighthouse and puppeteer
        run: npm install -g @unlighthouse/cli puppeteer
      - name: desktop prod site workflow
        if: contains(github.ref, 'main')
        run: unlighthouse-ci --site fcccanada.ca --desktop --reporter jsonExpanded --budget 90
      - name: desktop dev site workflow
        if: contains(github.ref, 'dev')
        run: unlighthouse-ci --site dev.fcccanada.ca --desktop --reporter jsonExpanded --budget 90
